name: CSV Generator
on:
  push:
    branches: [ main ]
jobs:
  generate-csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Generate CSV
      run: node generate-csv.js

    - name: Upload CSV
      uses: actions/upload-artifact@v2
      with:
        name: csv
        path: ./parameter_commaseparated.csv
