name: Extract table values
on:
  push:
    branches:
      - add-github-actions
jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install pandoc
        run: sudo apt-get install pandoc
      - name: Extract third table values
        run: |
          # Get the third table from README.md as HTML
          pandoc README.md -t html | grep -oP '<table>.*?</table>' | sed -n '3p' > table.html
          # Parse the HTML table and print the values as a comma-separated list
          python -c "import pandas as pd; df = pd.read_html('table.html')[0]; print(df.to_csv(header=None, index=None))"
          # Save the output as output.csv
          python -c "import pandas as pd; df = pd.read_html('table.html')[0]; df.to_csv('output.csv', header=None, index=None)"
      - name: Commit and push output.csv
        run: |
          git config --global user.email "github@henriksoderlund.com"
          git config --global user.name "HENRIK SÖDERLUND"
          git add output.csv
          git commit -am "Extracted values from third markdown table"
          git commit -m "Update output.csv" || exit 0
          git push
