name: Process README

on:
  push:
    branches:
      - add-github-actions

jobs:
  process_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
      - name: Process README.md
        run: python .github/scripts/process_readme.py
      - name: Commit changes
        run: |
          git config --global user.email "github@henriksoderlund.com"
          git config --global user.name "HENRIK SÖDERLUND"
          git add output.csv
          git commit -am "Extracted values from third markdown table"
          git commit -m "Update output.csv" || exit 0
          git push
