name: Extract table values
on:
  push:
    branches:
      - add-github-actions
jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Extract third table values
        run: |
          # Get the third table from README.md as a string
          table=$(awk '/^|/{c++} c==3' README.md)
          # Remove the header row and the separators
          table=$(echo "$table" | sed '1d;2d;$d')
          # Replace the pipe characters with commas
          table=$(echo "$table" | tr '|' ',')
          # Trim the leading and trailing spaces
          table=$(echo "$table" | sed 's/^ *//;s/ *$//')
          # Print the table as a comma-separated list
          echo "$table"
          # Save the output as output.csv
          echo "$table" > output.csv
      - name: Commit and push output.csv
        run: |
          git config --global user.email "github@henriksoderlund.com"
          git config --global user.name "HENRIK SÖDERLUND"
          git add output.csv
          git commit -am "Extracted values from third markdown table"
          git commit -m "Update output.csv" || exit 0
          git push
